apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a3zgb54pg-go 
  janus-idp.io/tekton: a3zgb54pg-go
  backstage.io/kubernetes-id: a3zgb54pg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a3zgb54pg-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  