apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: a3zgb54pg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: a3zgb54pg-go 
  name: a3zgb54pg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: a3zgb54pg-go 
